#!/bin/sh

# shellcheck source=bin/lib/output.sh
. "$(dirname "$0")/../bin/lib/output.sh"

# check if commit amend
result=$(ps -ocommand= -p $PPID | grep -c ' --amend')
# check if the current branch previous commit message is the same as the committed one
if [ "$result" -eq 0 ]; then
  prevMessage=$(git log --no-merges -1 --pretty=format:%B)
  INPUT_FILE=$1
  newMessage=`head -n1 $INPUT_FILE`
  if [ "$newMessage" = "$prevMessage" ]; then
    output "Commit message is the same as the one from the previous commit. Use amend or change commit message." "error"
    exit 1
  fi
fi
