#!/bin/sh

# shellcheck source=bin/lib/output.sh
. "$(dirname "$0")/../bin/lib/output.sh"

# shellcheck source=.githooks/commands/.post-merge
configFile="$(dirname "$0")/../.githooks/commands/.post-merge"

newAndChangedFiles=$(git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD)

executeCommandsByCondition() {
  while IFS=, read -r filePathStartsWith command
  do
    for filename in $newAndChangedFiles
    do
      case "$filename" in
        $filePathStartsWith*)
          output "Post merge command:" "heading"
          output "$command" "info"
          setsid sh -c "./../$command < /dev/stdout"
        ;;
      esac
    done
  done < "$configFile"
}

executeCommandsByCondition
