version: '3.6'

services:
    php:
        build:
            context: docker
            args:
                - PUID=${PUID}
                - GUID=${GUID}
        env_file:
            - .env
        volumes:
            - ./docker/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
            - ./code/:/var/www/code
            - ./composer/cache:/home/www-data/.composer/cache
