version: '3.7'

services:
    php: &php
        build: &build
            context: docker
            args:
                - PUID=${PUID}
                - GUID=${GUID}
        env_file:
            - .env
        volumes:
            - ./docker/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
            - ./docker/php-fpm-overrides.conf:/usr/local/etc/php-fpm.d/zzz-overrides.conf
            - ./code/:/var/www/code
            - ./composer/cache:/home/www-data/.composer/cache
            - ./vendors:/var/www/vendors

    php7_1:
        <<: *php
        build:
            <<: *build
            dockerfile: Dockerfile7_1
